Repository haskell/haskell-language-server, pull requests merged in 2021-01, with the labels that each got.

#1145 Remove no longer needed git submodule update
  install/src/HlsInstall.hs
Labels: merge me

#760 Fix suggestAddTypeAnnotation regex
  ghcide/src/Development/IDE/Plugin/CodeAction.hs
  ghcide/test/exe/Main.hs
Labels: merge me

#1143 Enable more tests
  test/functional/Command.hs
  test/functional/Diagnostic.hs
  test/functional/FunctionalCodeAction.hs
  test/functional/FunctionalLiquid.hs
  test/functional/HieBios.hs
  test/functional/Rename.hs
  test/testdata/rename/Rename.hs
  test/testdata/testdata.cabal
  test/testdata/wErrorTest/cabal.project
  test/testdata/wErrorTest/hie.yaml
Labels: merge me

#1142 Update links to issues/PRs in ghcide tests.
  ghcide/test/exe/Main.hs
Labels: merge me

#763 Delete unused testdata
  test/testdata/ApplyRefactError.hs
  test/testdata/CodeActionImportBrittany.hs
  test/testdata/CodeActionImportList.hs
  test/testdata/CodeActionImportListElaborate.hs
  test/testdata/FileWithWarning.hs
  test/testdata/GhcModCaseSplit.hs
  test/testdata/HaReCase.hs
  test/testdata/HaReDemote.hs
  test/testdata/HaReGA1/HaReGA1.cabal
  test/testdata/HaReGA1/HaReGA1.hs
  test/testdata/HaReGA1/cabal.project
  test/testdata/HaReLift.hs
  test/testdata/HaReMoveDef.hs
  test/testdata/HaReRename.hs
  test/testdata/HlintNoRefactorings.hs
  test/testdata/HlintParseFail.hs
  test/testdata/HlintPragma.hs
  test/testdata/Types.hs
  test/testdata/testdata.cabal
  test/testdata/typedHoleDiag.txt
  test/testdata/typedHoleDiag2.txt
  test/testdata/typedHoleDiag3.txt
  test/testdata/wrapper/8.8.1/Setup.hs
  test/testdata/wrapper/8.8.1/cabal1.cabal
  test/testdata/wrapper/8.8.1/src/Foo/Bar.hs
  test/testdata/wrapper/8.8.1/src/main.hs
  test/testdata/wrapper/ghc/dummy
  test/testdata/wrapper/lts-14.18/Setup.hs
  test/testdata/wrapper/lts-14.18/cabal1.cabal
  test/testdata/wrapper/lts-14.18/src/Foo/Bar.hs
  test/testdata/wrapper/lts-14.18/src/main.hs
Labels: merge me

#766 Also suggest importing methods without parent class
  ghcide/src/Development/IDE/Plugin/CodeAction.hs
  ghcide/src/Development/IDE/Types/Exports.hs
  ghcide/test/exe/Main.hs
Labels: merge me

#781 Fix #723 (Instance declarations in hs-boot files result in GHC errors)
  ghcide/src/Development/IDE/Core/Compile.hs
  ghcide/test/data/boot/A.hs
  ghcide/test/data/boot/A.hs-boot
  ghcide/test/exe/Main.hs
Labels: merge me

#1162 Fix wrong component name of splice plugin in hie.yaml
  hie-cabal.yaml
Labels: merge me

#764 Delete unused utilities for controlling logging.
  test/functional/FunctionalBadProject.hs
  test/utils/Test/Hls/Util.hs
Labels: merge me

#1146 Bump haskell-lsp to 0.23
  ghcide/ghcide.cabal
  ghcide/src/Development/IDE/Plugin/Completions/Logic.hs
  haskell-language-server.cabal
  hls-plugin-api/hls-plugin-api.cabal
  plugins/default/src/Ide/Plugin/Example.hs
  plugins/default/src/Ide/Plugin/Example2.hs
  plugins/default/src/Ide/Plugin/Pragmas.hs
  plugins/tactics/hls-tactics-plugin.cabal
  stack-8.10.1.yaml
  stack-8.10.2.yaml
  stack-8.10.3.yaml
  stack-8.6.4.yaml
  stack-8.6.5.yaml
  stack-8.8.2.yaml
  stack-8.8.3.yaml
  stack-8.8.4.yaml
  stack.yaml
Labels: merge me

#1166 Quick fix for #1158
  plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Parse/Token.hs
Labels: merge me

#1176 Prepare for Hackage
  haskell-language-server.cabal
  plugins/hls-class-plugin/hls-class-plugin.cabal
  plugins/hls-eval-plugin/hls-eval-plugin.cabal
  plugins/hls-explicit-imports-plugin/hls-explicit-imports-plugin.cabal
  plugins/hls-haddock-comments-plugin/hls-haddock-comments-plugin.cabal
  plugins/hls-hlint-plugin/hls-hlint-plugin.cabal
  plugins/hls-retrie-plugin/hls-retrie-plugin.cabal
  plugins/hls-splice-plugin/hls-splice-plugin.cabal
Labels: merge me

#1165 Suggest adding pragmas for parse errors too
  plugins/default/src/Ide/Plugin/Pragmas.hs
  test/functional/FunctionalCodeAction.hs
  test/testdata/addPragmas/NeedsPragmas.hs
  test/testdata/addPragmas/TypeApplications.hs
  test/testdata/addPragmas/hie.yaml
  test/testdata/addPragmas/test.cabal
Labels: merge me, type: enhancement

#1181 Preparation for uploading `hls-exactprint-utils`
  hls-exactprint-utils/LICENSE
  hls-exactprint-utils/hls-exactprint-utils.cabal
Labels: merge me

#1177 Make adding missing constraint work in presence of 'forall' (fixes #1164)
  ghcide/src/Development/IDE/GHC/Compat.hs
  ghcide/src/Development/IDE/Plugin/CodeAction.hs
  ghcide/test/exe/Main.hs
Labels: merge me

#1180 Complete hls-hlint-plugin package metadata
  plugins/hls-hlint-plugin/hls-hlint-plugin.cabal
Labels: merge me

#1182 Preparation for Uploading Splice Plugin to Hackage
  plugins/hls-splice-plugin/hls-splice-plugin.cabal
Labels: merge me

#1183 Installation from Hackage - add README section
  README.md
Labels: merge me

#1178 Benchmark improvements
  .github/workflows/test.yml
  ghcide/bench/config.yaml
  ghcide/bench/exe/Main.hs
  ghcide/bench/hist/Main.hs
  ghcide/bench/lib/Experiments.hs
  ghcide/bench/lib/Experiments/Types.hs
  shake-bench/src/Development/Benchmark/Rules.hs
Labels: merge me

#1185 Update package description of haddock comments plugin
  plugins/hls-haddock-comments-plugin/hls-haddock-comments-plugin.cabal
Labels: merge me

#1189 Switch module outline to useWtihStale
  ghcide/src/Development/IDE/LSP/Outline.hs
Labels: merge me

#1190 Do not disable parallel GC
  ghcide/ghcide.cabal
  haskell-language-server.cabal
Labels: merge me

#1186 Fix class plugin cabal
  plugins/hls-class-plugin/hls-class-plugin.cabal
Labels: merge me

#1188 Fix sticky diagnostics
  ghcide/ghcide.cabal
  ghcide/src/Development/IDE/Core/Shake.hs
  ghcide/src/Development/IDE/Core/Tracing.hs
  ghcide/src/Development/IDE/Types/Shake.hs
  ghcide/test/exe/Main.hs
Labels: merge me

#1191 Update nixpkgs to ghc 8.10.3
  .github/workflows/nix.yml
  nix/default.nix
  nix/sources.json
Labels: merge me

#1194 Remove runs dropped by #1173
  .github/mergify.yml
Labels: merge me

#1173 Test only last ghc minor version and fix windows cache
  .github/mergify.yml
  .github/workflows/test.yml
  cabal.project
  ghcide/ghcide.cabal
  haskell-language-server.cabal
Labels: merge me

#1195 Use completionSnippetsOn flag
  README.md
  ghcide/src/Development/IDE/Plugin/Completions.hs
  test/functional/Completion.hs
Labels: merge me

#1198 Disable win 8.6.4 job
  .github/mergify.yml
  .github/workflows/test.yml
Labels: merge me

#1199 Minor eval plugin fixes
  hie-cabal.yaml
  hie-stack.yaml
  plugins/hls-eval-plugin/hls-eval-plugin.cabal
Labels: merge me

#1202 Fix bug in Retrie "fold/unfold in local file" commands
  plugins/hls-retrie-plugin/src/Ide/Plugin/Retrie.hs
Labels: merge me

#1204 Stale diagnostics fix
  ghcide/src/Development/IDE/Core/Shake.hs
  ghcide/test/exe/Main.hs
Labels: merge me

#1203 Extract Development.IDE.GHC.ExactPrint
  cabal.project
  ghcide/.hlint.yaml
  ghcide/ghcide.cabal
  ghcide/src/Development/IDE/GHC/ExactPrint.hs
  hie-cabal.yaml
  hie-stack.yaml
  hls-exactprint-utils/LICENSE
  hls-exactprint-utils/hls-exactprint-utils.cabal
  nix/default.nix
  plugins/hls-splice-plugin/hls-splice-plugin.cabal
  plugins/hls-splice-plugin/src/Ide/Plugin/Splice.hs
  plugins/tactics/hls-tactics-plugin.cabal
  plugins/tactics/src/Ide/Plugin/Tactic.hs
  shell.nix
  stack-8.10.1.yaml
  stack-8.10.2.yaml
  stack-8.10.3.yaml
  stack-8.6.4.yaml
  stack-8.6.5.yaml
  stack-8.8.2.yaml
  stack-8.8.3.yaml
  stack-8.8.4.yaml
  stack.yaml
Labels: merge me

#1206 Documentation for the Eval Plugin
  README.md
  plugins/hls-eval-plugin/README.md
  plugins/hls-eval-plugin/demo.gif
  plugins/hls-eval-plugin/hls-eval-plugin.cabal
  plugins/hls-eval-plugin/src/Ide/Plugin/Eval.hs
  plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Tutorial.hs
Labels: merge me

#635 Leverage last apply-refact improvements in hlint plugin (include getParsedModuleWithComments in ghcide)
  .github/workflows/bench.yml
  .github/workflows/test.yml
  cabal.project
  ghcide/src/Development/IDE/Core/RuleTypes.hs
  ghcide/src/Development/IDE/Core/Rules.hs
  plugins/hls-hlint-plugin/hls-hlint-plugin.cabal
  plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs
  stack-8.10.1.yaml
  stack-8.10.2.yaml
  stack-8.10.3.yaml
  stack-8.6.4.yaml
  stack-8.6.5.yaml
  stack-8.8.2.yaml
  stack-8.8.3.yaml
  stack-8.8.4.yaml
  stack.yaml
  test/functional/FunctionalCodeAction.hs
  test/testdata/hlint/ApplyRefact6.hs
  test/testdata/hlint/hie.yaml
Labels: merge me

#1209 Expose shake options used
  ghcide/CHANGELOG.md
  ghcide/exe/Main.hs
  ghcide/ghcide.cabal
  ghcide/src/Development/IDE/Core/Service.hs
  ghcide/src/Development/IDE/Types/Options.hs
  src/Ide/Main.hs
Labels: merge me

#1212 Parenthesise type operators when extending import lists
  ghcide/src/Development/IDE/Types/Exports.hs
  ghcide/test/exe/Main.hs
Labels: merge me

#1219 Ignore .shake folder
  .gitignore
Labels: merge me

#1220 Fix changelog dates
  ghcide/CHANGELOG.md
Labels: merge me

#1221 Use exact print for suggest missing constraint code actions
  ghcide/ghcide.cabal
  ghcide/src/Development/IDE/Core/Rules.hs
  ghcide/src/Development/IDE/GHC/ExactPrint.hs
  ghcide/src/Development/IDE/GHC/Orphans.hs
  ghcide/src/Development/IDE/Plugin/CodeAction.hs
  ghcide/src/Development/IDE/Plugin/CodeAction/ExactPrint.hs
  ghcide/test/exe/Main.hs
Labels: merge me

#1222 Add traces for HLS providers
  ghcide/.hlint.yaml
  ghcide/src/Development/IDE/Core/Tracing.hs
  ghcide/src/Development/IDE/LSP/LanguageServer.hs
  ghcide/src/Development/IDE/LSP/Server.hs
  ghcide/src/Development/IDE/Plugin/HLS.hs
Labels: merge me

#1218 Limit completions to top 40
  README.md
  ghcide/src/Development/IDE/Plugin/Completions.hs
  ghcide/src/Development/IDE/Plugin/Completions/Logic.hs
  ghcide/test/exe/Main.hs
  hls-plugin-api/src/Ide/Plugin/Config.hs
  test/functional/Completion.hs
Labels: merge me

#1224 Add note in README/Tutorial regarding CPP support
  plugins/hls-eval-plugin/README.md
Labels: merge me

#1223 Test and fix for issue 1213
  plugins/hls-eval-plugin/src/Ide/Plugin/Eval/CodeLens.hs
  plugins/hls-eval-plugin/test/Eval.hs
  plugins/hls-eval-plugin/test/testdata/TLastLine.hs.expected
Labels: merge me

#1225 Use the runtime ghc libdir for ghc-exactprint
  cabal.project
  plugins/default/src/Ide/Plugin/Brittany.hs
  plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs
  stack-8.10.1.yaml
  stack-8.10.2.yaml
  stack-8.10.3.yaml
  stack-8.6.4.yaml
  stack-8.6.5.yaml
  stack-8.8.2.yaml
  stack-8.8.3.yaml
  stack-8.8.4.yaml
  stack.yaml
Labels: component: hlint plugin, merge me

#1234 Change packages metadata and rename tactics subfolder
  cabal.project
  haskell-language-server.cabal
  hls-plugin-api/hls-plugin-api.cabal
  nix/default.nix
  plugins/hls-hlint-plugin/hls-hlint-plugin.cabal
  plugins/hls-tactics-plugin/hls-tactics-plugin.cabal
  plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic.hs
  plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic/Auto.hs
  plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic/CodeGen.hs
  plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic/Context.hs
  plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic/Debug.hs
  plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic/GHC.hs
  plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic/Judgements.hs
  plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic/KnownStrategies.hs
  plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic/KnownStrategies/QuickCheck.hs
  plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic/Machinery.hs
  plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic/Naming.hs
  plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic/Range.hs
  plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic/Tactics.hs
  plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic/TestTypes.hs
  plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic/Types.hs
  plugins/hls-tactics-plugin/test/AutoTupleSpec.hs
  plugins/hls-tactics-plugin/test/Main.hs
  plugins/hls-tactics-plugin/test/UnificationSpec.hs
  stack-8.10.1.yaml
  stack-8.10.2.yaml
  stack-8.10.3.yaml
  stack-8.6.4.yaml
  stack-8.6.5.yaml
  stack-8.8.2.yaml
  stack-8.8.3.yaml
  stack-8.8.4.yaml
  stack.yaml
Labels: merge me

#1233 Fix the bug that generating comments would duplicate existing comments
  plugins/hls-haddock-comments-plugin/src/Ide/Plugin/HaddockComments.hs
  test/functional/HaddockComments.hs
  test/testdata/haddockComments/MultivariateFunction.expected.hs
  test/testdata/haddockComments/MultivariateFunction.hs
  test/testdata/haddockComments/Record.expected.hs
  test/testdata/haddockComments/Record.hs
Labels: merge me

#1238 Complete the No- variants of language extensions and Strict extension
  plugins/default/src/Ide/Plugin/Pragmas.hs
  test/functional/Completion.hs
Labels: merge me

#1243 Add non reversable pragma completion
  plugins/default/src/Ide/Plugin/Pragmas.hs
Labels: merge me

#1235 Add code actions for disabling a warning in the current file
  ghcide/src/Development/IDE/GHC/Warnings.hs
  ghcide/src/Development/IDE/Plugin/CodeAction.hs
  ghcide/test/exe/Main.hs
  test/functional/Class.hs
  test/functional/FunctionalCodeAction.hs
Labels: merge me

#1249 Add dynamic linking common issue
  README.md
Labels: merge me

#1251 Add gh workflows badges
  README.md
Labels: merge me

#1248 Add license for hls-tactics-plugin
  plugins/hls-tactics-plugin/LICENSE
  plugins/hls-tactics-plugin/hls-tactics-plugin.cabal
Labels: merge me

#1193 Remove undefined exports suggestions
  ghcide/src/Development/IDE/Plugin/CodeAction.hs
  ghcide/src/Development/IDE/Plugin/CodeAction/PositionIndexed.hs
  ghcide/test/exe/Main.hs
  hls-plugin-api/src/Ide/PluginUtils.hs
Labels: merge me

#1253 Benchmarks: generate heap profiles
  .github/mergify.yml
  .github/workflows/bench.yml
  ghcide/bench/hist/Main.hs
  ghcide/ghcide.cabal
  shake-bench/src/Development/Benchmark/Rules.hs
Labels: merge me

#1254 Update bench.yml to include all the relevant artifacts
  .github/workflows/bench.yml
Labels: merge me

#1255 Reorder code actions to put remove redundant imports first
  ghcide/src/Development/IDE/Plugin/CodeAction.hs
Labels: merge me

#1261 Produce heap profiles the old fashioned way, from .hp files
  ghcide/bench/hist/Main.hs
  ghcide/ghcide.cabal
  shake-bench/src/Development/Benchmark/Rules.hs
Labels: merge me

#1267 Add the new logos
  README.md
  docs/logos/logo-1024.png
  docs/logos/logo-128.png
  docs/logos/logo-256.png
  docs/logos/logo-32.png
  docs/logos/logo-512.png
  docs/logos/logo-64.png
  docs/logos/logo.svg
Labels: merge me

#1265 Fix a bug in completions
  ghcide/src/Development/IDE/Plugin/HLS.hs
Labels: merge me

#1268 Tighten dependency on apply-refact
  plugins/hls-hlint-plugin/hls-hlint-plugin.cabal
Labels: merge me

#1269 Do not error out on failed rewrite
  ghcide/src/Development/IDE/Plugin/CodeAction.hs
Labels: merge me

#1197 Add custom cache layer for session loading
  ghcide/session-loader/Development/IDE/Session.hs
Labels: merge me

#1271 Prepare 0.9.0
  ChangeLog.md
  docs/releases.md
  haskell-language-server.cabal
Labels: merge me

#704 References via `hiedb`
  cabal.project
  exe/Wrapper.hs
  ghcide/.hlint.yaml
  ghcide/bench/lib/Experiments.hs
  ghcide/exe/Arguments.hs
  ghcide/exe/Main.hs
  ghcide/ghcide.cabal
  ghcide/session-loader/Development/IDE/Session.hs
  ghcide/src/Development/IDE/Core/Compile.hs
  ghcide/src/Development/IDE/Core/FileExists.hs
  ghcide/src/Development/IDE/Core/FileStore.hs
  ghcide/src/Development/IDE/Core/OfInterest.hs
  ghcide/src/Development/IDE/Core/PositionMapping.hs
  ghcide/src/Development/IDE/Core/RuleTypes.hs
  ghcide/src/Development/IDE/Core/Rules.hs
  ghcide/src/Development/IDE/Core/Service.hs
  ghcide/src/Development/IDE/Core/Shake.hs
  ghcide/src/Development/IDE/GHC/Compat.hs
  ghcide/src/Development/IDE/GHC/Error.hs
  ghcide/src/Development/IDE/GHC/Util.hs
  ghcide/src/Development/IDE/Import/DependencyInformation.hs
  ghcide/src/Development/IDE/Import/FindImports.hs
  ghcide/src/Development/IDE/LSP/HoverDefinition.hs
  ghcide/src/Development/IDE/LSP/LanguageServer.hs
  ghcide/src/Development/IDE/LSP/Server.hs
  ghcide/src/Development/IDE/Plugin/Completions/Logic.hs
  ghcide/src/Development/IDE/Spans/AtPoint.hs
  ghcide/src/Development/IDE/Spans/Common.hs
  ghcide/src/Development/IDE/Spans/Documentation.hs
  ghcide/src/Development/IDE/Spans/LocalBindings.hs
  ghcide/src/Development/IDE/Types/Shake.hs
  ghcide/test/data/references/Main.hs
  ghcide/test/data/references/OtherModule.hs
  ghcide/test/data/references/OtherOtherModule.hs
  ghcide/test/data/references/References.hs
  ghcide/test/data/references/hie.yaml
  ghcide/test/exe/Main.hs
  haskell-language-server.cabal
  plugins/hls-class-plugin/src/Ide/Plugin/Class.hs
  plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic.hs
  src/Ide/Arguments.hs
  src/Ide/Main.hs
  stack-8.10.1.yaml
  stack-8.10.2.yaml
  stack-8.10.3.yaml
  stack-8.6.4.yaml
  stack-8.6.5.yaml
  stack-8.8.2.yaml
  stack-8.8.3.yaml
  stack-8.8.4.yaml
  stack.yaml
  test/functional/Highlight.hs
  test/functional/Progress.hs
  test/functional/TypeDefinition.hs
  test/utils/Test/Hls/Util.hs
Labels: merge me

#1275 Update IRC Name in README
  README.md
Labels: merge me

#1273 Restore code actions order
  ghcide/src/Development/IDE/Plugin/CodeAction.hs
  ghcide/src/Development/IDE/Plugin/CodeAction/ExactPrint.hs
Labels: merge me

#1232 Doctest comment parsing using module annotations in Eval Plugin
  ghcide/src/Development/IDE/Core/Rules.hs
  ghcide/src/Development/IDE/GHC/Orphans.hs
  plugins/hls-eval-plugin/hls-eval-plugin.cabal
  plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Code.hs
  plugins/hls-eval-plugin/src/Ide/Plugin/Eval/CodeLens.hs
  plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Parse/Comments.hs
  plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Parse/Option.hs
  plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Parse/Parser.hs
  plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Parse/Section.hs
  plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Parse/Token.hs
  plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Types.hs
  plugins/hls-eval-plugin/test/Eval.hs
  plugins/hls-eval-plugin/test/testdata/TEndingMulti.hs
  plugins/hls-eval-plugin/test/testdata/TEndingMulti.hs.expected
  plugins/hls-eval-plugin/test/testdata/THaddock.hs
  plugins/hls-eval-plugin/test/testdata/THaddock.hs.expected
  plugins/hls-eval-plugin/test/testdata/TLastLine.hs
  plugins/hls-eval-plugin/test/testdata/TMulti.hs
  plugins/hls-eval-plugin/test/testdata/TMulti.hs.expected
  plugins/hls-eval-plugin/test/testdata/TNested.hs
  plugins/hls-eval-plugin/test/testdata/TNested.hs.expected
  plugins/hls-eval-plugin/test/testdata/TUNPACK.hs
  plugins/hls-eval-plugin/test/testdata/TUNPACK.hs.expected
  plugins/hls-eval-plugin/test/testdata/test.cabal
  stack-8.10.1.yaml
  stack-8.6.4.yaml
  stack-8.6.5.yaml
  stack-8.8.2.yaml
  stack-8.8.3.yaml
  stack-8.8.4.yaml
  stack.yaml
  test/utils/Test/Hls/Util.hs
Labels: merge me

#1264 ghcide: Implements a CodeAction to disambiguate ambiguous symbols
  ghcide/src/Development/IDE/GHC/Error.hs
  ghcide/src/Development/IDE/GHC/Orphans.hs
  ghcide/src/Development/IDE/Plugin/CodeAction.hs
  ghcide/src/Development/IDE/Plugin/CodeAction/ExactPrint.hs
  ghcide/src/Development/IDE/Spans/Common.hs
  ghcide/test/data/hiding/AVec.hs
  ghcide/test/data/hiding/BVec.hs
  ghcide/test/data/hiding/CVec.hs
  ghcide/test/data/hiding/DVec.hs
  ghcide/test/data/hiding/EVec.hs
  ghcide/test/data/hiding/HideFunction.hs
  ghcide/test/data/hiding/HideFunction.hs.expected.append.E
  ghcide/test/data/hiding/HideFunction.hs.expected.append.Prelude
  ghcide/test/data/hiding/HideFunction.hs.expected.fromList.A
  ghcide/test/data/hiding/HideFunction.hs.expected.fromList.B
  ghcide/test/data/hiding/HideFunction.hs.expected.qualified.append.Prelude
  ghcide/test/data/hiding/HideFunction.hs.expected.qualified.fromList.E
  ghcide/test/data/hiding/HidePreludeIndented.hs
  ghcide/test/data/hiding/HidePreludeIndented.hs.expected
  ghcide/test/data/hiding/HideType.hs
  ghcide/test/data/hiding/HideType.hs.expected.A
  ghcide/test/data/hiding/HideType.hs.expected.E
  ghcide/test/data/hiding/hie.yaml
  ghcide/test/exe/Main.hs
  plugins/hls-splice-plugin/src/Ide/Plugin/Splice.hs
Labels: merge me

#1266 Reenable auto extend imports and drop snippets for infix completions
  ghcide/ghcide.cabal
  ghcide/src/Development/IDE/GHC/Compat.hs
  ghcide/src/Development/IDE/Plugin/CodeAction/ExactPrint.hs
  ghcide/src/Development/IDE/Plugin/Completions.hs
  ghcide/src/Development/IDE/Plugin/Completions/Logic.hs
  ghcide/src/Development/IDE/Plugin/Completions/Types.hs
  ghcide/test/exe/Main.hs
  ghcide/test/src/Development/IDE/Test.hs
  plugins/hls-explicit-imports-plugin/src/Ide/Plugin/ExplicitImports.hs
  test/functional/Completion.hs
Labels: merge me
