Repository haskell/haskell-language-server, pull requests merged in 2024-07, with the labels that each got.

#4342 capture error in worker thread
  ghcide/src/Development/IDE/Core/WorkerThread.hs
Labels: performance

#4347 Fix core file location in `GetLinkable`
  ghcide/src/Development/IDE/Core/Compile.hs
  ghcide/src/Development/IDE/Core/Rules.hs
Labels: performance

#4235 Provide explicit import in inlay hints
  hls-plugin-api/src/Ide/Plugin/Config.hs
  hls-plugin-api/src/Ide/Plugin/ConfigUtils.hs
  hls-plugin-api/src/Ide/Types.hs
  hls-test-utils/src/Test/Hls/Util.hs
  plugins/hls-explicit-imports-plugin/src/Ide/Plugin/ExplicitImports.hs
  plugins/hls-explicit-imports-plugin/test/Main.hs
  test/testdata/schema/ghc94/default-config.golden.json
  test/testdata/schema/ghc94/vscode-extension-schema.golden.json
  test/testdata/schema/ghc96/default-config.golden.json
  test/testdata/schema/ghc96/vscode-extension-schema.golden.json
  test/testdata/schema/ghc98/default-config.golden.json
  test/testdata/schema/ghc98/vscode-extension-schema.golden.json
Labels: merge me

#3273 Add codeactions for cabal field names
  haskell-language-server.cabal
  plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal.hs
  plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal/FieldSuggest.hs
  plugins/hls-cabal-plugin/test/Main.hs
  plugins/hls-cabal-plugin/test/Utils.hs
  plugins/hls-cabal-plugin/test/testdata/code-actions/FieldSuggestions.cabal
  plugins/hls-cabal-plugin/test/testdata/code-actions/FieldSuggestions.golden.cabal
Labels: status: needs review
