Repository haskell/haskell-language-server, pull requests merged in 2024-05, with the labels that each got.

#4209 Force complete pattern in ghcide
  ghcide/ghcide.cabal
  ghcide/src/Development/IDE/GHC/CoreFile.hs
  ghcide/src/Development/IDE/GHC/Orphans.hs
  ghcide/src/Development/IDE/LSP/Notifications.hs
Labels: status: needs review

#4190 Stabilize the build system by correctly house keeping the dirtykeys and rule values [flaky test #4185 #4093]
  ghcide/session-loader/Development/IDE/Session.hs
  ghcide/src/Development/IDE/Core/FileExists.hs
  ghcide/src/Development/IDE/Core/FileStore.hs
  ghcide/src/Development/IDE/Core/OfInterest.hs
  ghcide/src/Development/IDE/Core/Shake.hs
  ghcide/src/Development/IDE/Core/Tracing.hs
  ghcide/src/Development/IDE/LSP/Notifications.hs
  ghcide/src/Development/IDE/Main.hs
  hls-graph/src/Development/IDE/Graph/Internal/Database.hs
  hls-graph/src/Development/IDE/Graph/Internal/Types.hs
  hls-graph/test/ActionSpec.hs
  hls-graph/test/DatabaseSpec.hs
  hls-graph/test/Example.hs
  plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal.hs
  plugins/hls-eval-plugin/src/Ide/Plugin/Eval/CodeLens.hs
Labels: priority: high, status: needs review

#4191 Prepare release 2.8.0.0
  .github/workflows/release.yaml
  ChangeLog.md
  docs/support/ghc-version-support.md
  ghcide/ghcide.cabal
  haskell-language-server.cabal
  hls-graph/hls-graph.cabal
  hls-plugin-api/hls-plugin-api.cabal
  hls-test-utils/hls-test-utils.cabal
Labels: merge me

#4207 [Migrate diagnosticTests] part of #4173 Migrate ghcide tests to hls test utils
  ghcide/exe/Main.hs
  ghcide/src/Development/IDE/Main.hs
  ghcide/test/exe/ClientSettingsTests.hs
  ghcide/test/exe/CodeLensTests.hs
  ghcide/test/exe/CompletionTests.hs
  ghcide/test/exe/Config.hs
  ghcide/test/exe/DiagnosticTests.hs
  ghcide/test/exe/ExceptionTests.hs
  ghcide/test/exe/InitializeResponseTests.hs
  ghcide/test/exe/OpenCloseTest.hs
  ghcide/test/exe/THTests.hs
  ghcide/test/exe/TestUtils.hs
  ghcide/test/exe/UnitTests.hs
  hls-test-utils/src/Test/Hls.hs
  plugins/hls-refactor-plugin/test/Main.hs
  plugins/hls-semantic-tokens-plugin/test/SemanticTokensTest.hs
  test/functional/Config.hs
Labels: status: in discussion, status: needs review

#4241 Enable test for #717
  ghcide/test/exe/FindDefinitionAndHoverTests.hs
Labels: flaky test

#3952 3944 extend the properties api to better support nested configuration
  ghcide/src/Development/IDE/Core/Rules.hs
  hls-plugin-api/hls-plugin-api.cabal
  hls-plugin-api/src/Ide/Plugin/Properties.hs
  hls-plugin-api/test/Ide/PluginUtilsTest.hs
  hls-plugin-api/test/testdata/Property/NestedPropertyDefault.json
  hls-plugin-api/test/testdata/Property/NestedPropertyVscode.json
Labels: status: needs review

#4231 Refactor hls-test-util and reduce getCurrentDirectory after initilization
  exe/Wrapper.hs
  ghcide/exe/Main.hs
  ghcide/session-loader/Development/IDE/Session.hs
  ghcide/src/Development/IDE.hs
  ghcide/src/Development/IDE/Core/Rules.hs
  ghcide/src/Development/IDE/Core/Service.hs
  ghcide/src/Development/IDE/Core/Shake.hs
  ghcide/src/Development/IDE/LSP/LanguageServer.hs
  ghcide/src/Development/IDE/Main.hs
  ghcide/src/Development/IDE/Types/HscEnvEq.hs
  ghcide/test/exe/BootTests.hs
  ghcide/test/exe/CPPTests.hs
  ghcide/test/exe/ClientSettingsTests.hs
  ghcide/test/exe/CodeLensTests.hs
  ghcide/test/exe/Config.hs
  ghcide/test/exe/CradleTests.hs
  ghcide/test/exe/DependentFileTest.hs
  ghcide/test/exe/DiagnosticTests.hs
  ghcide/test/exe/ExceptionTests.hs
  ghcide/test/exe/GarbageCollectionTests.hs
  ghcide/test/exe/IfaceTests.hs
  ghcide/test/exe/InitializeResponseTests.hs
  ghcide/test/exe/Main.hs
  ghcide/test/exe/ReferenceTests.hs
  ghcide/test/exe/THTests.hs
  ghcide/test/exe/TestUtils.hs
  ghcide/test/exe/UnitTests.hs
  haskell-language-server.cabal
  hls-plugin-api/src/Ide/PluginUtils.hs
  hls-test-utils/hls-test-utils.cabal
  hls-test-utils/src/Test/Hls.hs
  hls-test-utils/src/Test/Hls/Util.hs
  plugins/hls-hlint-plugin/test/Main.hs
  plugins/hls-module-name-plugin/src/Ide/Plugin/ModuleName.hs
  plugins/hls-notes-plugin/test/NotesTest.hs
  plugins/hls-refactor-plugin/test/Main.hs
  plugins/hls-rename-plugin/test/Main.hs
  plugins/hls-retrie-plugin/src/Ide/Plugin/Retrie.hs
  plugins/hls-semantic-tokens-plugin/test/SemanticTokensTest.hs
  plugins/hls-splice-plugin/test/Main.hs
  plugins/hls-stan-plugin/test/Main.hs
  src/Ide/Main.hs
  test/functional/Config.hs
Labels: status: needs review, flaky test

#4258 Migrate ClientSettingsTests
  ghcide/test/exe/ClientSettingsTests.hs
Labels: status: needs review

#4260 Migrate PreprocessorTests
  ghcide/test/exe/PreprocessorTests.hs
Labels: status: needs review

#4261 Migrate RootUriTests
  ghcide/test/exe/RootUriTests.hs
  hls-test-utils/src/Test/Hls.hs
Labels: status: needs review

#4269 Migrate WatchedFileTests
  ghcide/test/exe/WatchedFileTests.hs
Labels: status: needs review

#4268 Migrate UnitTests
  ghcide/test/exe/Main.hs
  ghcide/test/exe/UnitTests.hs
Labels: status: needs review
