Repository haskell/haskell-language-server, pull requests merged in 2025-04, with the labels that each got.

#4543 porting hls-refactor to ghc-9.12
  .github/workflows/test.yml
  haskell-language-server.cabal
  plugins/hls-refactor-plugin/src/Development/IDE/GHC/ExactPrint.hs
  plugins/hls-refactor-plugin/src/Development/IDE/Plugin/CodeAction.hs
  plugins/hls-refactor-plugin/src/Development/IDE/Plugin/CodeAction/ExactPrint.hs
  plugins/hls-refactor-plugin/src/Development/IDE/Plugin/Plugins/AddArgument.hs
  plugins/hls-refactor-plugin/test/Main.hs
  plugins/hls-refactor-plugin/test/Test/AddArgument.hs
  test/testdata/schema/ghc912/default-config.golden.json
  test/testdata/schema/ghc912/vscode-extension-schema.golden.json
Labels: status: needs review

#4551 Remove allow-newer for hiedb
  .circleci/config.yml
  cabal.project
  ghcide/ghcide.cabal
  haskell-language-server.cabal
  stack-lts22.yaml
  stack.yaml
Labels: merge me

#4542 add ghcide-bench flag to .cabal file
  haskell-language-server.cabal
Labels: performance, status: needs review
